apiVersion: v1
kind: Secret
metadata:
  name: task-api-secret
  namespace: 3-tier-app
type: Opaque
stringData:
  MONGO_URL: mongodb+srv://thinkbetterdailytips_db_user:W72kxA1QHCl9WGkM@task-app-cluster.w7hp9oc.mongodb.net/taskdb?appName=Task-App-Cluster
